<a href="https://colab.research.google.com/github/Karan15504/Civil-Aviation-Dashboard/blob/main/Civil_Aviation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [124]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [125]:
df = pd.read_excel("/content/DOM CITYPAIR DATA, JANUARY  2026 (2).xlsx", skiprows = 2)

In [126]:
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df

,s.no.,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2
0,1,ADAMPUR,MUMBAI,5278,5380,0,0.083,0,0
1,2,ADAMPUR,NANDED,578,-,0,-,0,-
2,3,ADAMPUR,Ghaziabad,1139,1514,0,0,0,0
3,4,AGARTALA,AHMEDABAD,-,206,-,0.793,-,0
4,5,AGARTALA,BAGDOGRA,2221,4287,0,0,0,0
...,...,...,...,...,...,...,...,...,...
654,655,MUMBAI,CHENNAI,4458,3289,2.42,0,0,0
655,656,MUMBAI,LUCKNOW,5026,5083,1.087,0,0,0
656,657,MUMBAI,HYDERABAD,7035,6732,6.588,0,0,0
657,SUB TOTAL,NaN,NaN,7569183,7678005,43590.979721,37495.697919,1942.942072,1711.465007
658,TOTAL,NaN,NaN,15247188,NaN,81086.67764,NaN,3654.407079,NaN

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 659 entries, 0 to 658
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   s.no.                    659 non-null    object
 1   city 1                   657 non-null    object
 2   city 2                   657 non-null    object
 3   passengers
to city 2    659 non-null    object
 4   passengers
from city 2  658 non-null    object
 5   freight
to city 2       659 non-null    object
 6   freight
from city 2     658 non-null    object
 7   mail
to city 2          659 non-null    object
 8   mail
from city 2        658 non-null    object
dtypes: object(9)
memory usage: 46.5+ KB

In [128]:
mask = ~df.astype(str).apply(lambda row: row.str.contains('SUB TOTAL|^TOTAL$', case=False).any(), axis=1)
df = df[mask]

In [129]:
df

,s.no.,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2
0,1,ADAMPUR,MUMBAI,5278,5380,0,0.083,0,0
1,2,ADAMPUR,NANDED,578,-,0,-,0,-
2,3,ADAMPUR,Ghaziabad,1139,1514,0,0,0,0
3,4,AGARTALA,AHMEDABAD,-,206,-,0.793,-,0
4,5,AGARTALA,BAGDOGRA,2221,4287,0,0,0,0
...,...,...,...,...,...,...,...,...,...
652,653,MUMBAI,JAIPUR,4799,4893,2.212,4.205,0,0
653,654,MUMBAI,MANGALORE,3711,4211,0,0.001,0,2.647
654,655,MUMBAI,CHENNAI,4458,3289,2.42,0,0,0
655,656,MUMBAI,LUCKNOW,5026,5083,1.087,0,0,0
656,657,MUMBAI,HYDERABAD,7035,6732,6.588,0,0,0

In [130]:
df.drop("s.no.", axis=1,inplace = True)

In [131]:
df['OD Pair'] = df['city 1'] + "-" + df['city 2']

In [132]:
df["passengers \nto city 2"].dtypes

dtype('O')

In [133]:
df["passengers \nfrom city 2"].dtypes

dtype('O')

In [134]:
df["passengers \nto city 2"].unique()

array([5278, 578, 1139, '-', 2221, 4007, 327, 6524, 858, 10097, 3245,
       1674, 35231, 797, 936, 1529, 2945, 171, 2157, 5358, 2076, 2626,
       1688, 4520, 5381, 1704, 50114, 4173, 4845, 10401, 27804, 4431,
       17061, 5183, 107213, 160, 2398, 118, 13432, 5060, 24239, 6464,
       10644, 519, 3077, 1276, 1532, 284, 5126, 258, 31727, 12484, 91101,
       1637, 2246, 6059, 326, 22044, 4484, 5140, 6396, 4349, 202, 3465,
       5323, 2565, 6531, 6382, 5683, 107, 402, 630, 1170, 1599, 482, 3753,
       892, 189, 5110, 1578, 10547, 4953, 183, 49163, 203, 2527, 2061,
       155, 14410, 4146, 5894, 2336, 45, 931, 13368, 2323, 10213, 21388,
       746, 5951, 55188, 4089, 434, 1315, 16343, 3469, 28407, 25279, 2308,
       3304, 4399, 3840, 2056, 490, 10824, 43447, 1485, 24191, 62794,
       18012, 45539, 814, 9025, 207251, 4842, 296, 5834, 33571, 12097,
       37994, 4462, 4149, 89055, 394, 20161, 4118, 36636, 5188, 2693,
       4438, 10940, 5123, 3688, 62865, 2038, 85825, 20828, 245, 29314,
       7729, 1372, 38313, 165911, 23269, 1593, 4598, 29350, 2207, 19967,
       75055, 10166, 2222, 5823, 21129, 1831, 6328, 1487, 374, 7468,
       13744, 9780, 2093, 35206, 2155, 13803, 5024, 34561, 1227, 14491,
       21964, 4396, 9903, 461, 5022, 26919, 2900, 17745, 3967, 2053, 7436,
       2295, 53221, 126, 843, 2216, 5218, 20463, 2718, 174, 134, 54, 420,
       1757, 3750, 17851, 2104, 27078, 1546, 4994, 3515, 2169, 69, 109,
       1943, 2249, 5111, 8947, 572, 1216, 190, 19, 439, 212, 6354, 6814,
       45854, 350, 5457, 551, 5, 10332, 4401, 5692, 345, 7107, 46, 2811,
       3984, 24272, 3900, 6104, 8859, 221, 36223, 5275, 528, 95009, 4835,
       4522, 16155, 59827, 6512, 10248, 66, 539, 1262, 149, 34040, 50866,
       3894, 4500, 22482, 2100, 100091, 2068, 5450, 29282, 37237, 6020,
       2067, 5781, 2023, 4785, 864, 3127, 11787, 14796, 8821, 812, 4874,
       4143, 16737, 3757, 2024, 19274, 86, 291, 25535, 336, 22712, 26,
       5437, 6, 51754, 27476, 8902, 4671, 4904, 5296, 5329, 66892, 1177,
       4084, 5701, 5037, 14369, 3976, 952, 10198, 24011, 4572, 421, 2913,
       2448, 156, 3294, 12852, 4003, 8077, 4058, 9001, 4987, 4796, 8492,
       55473, 21796, 68889, 3886, 4, 5363, 131514, 15451, 48063, 4821,
       7613, 28650, 12655, 25573, 5253, 17097, 2146, 3708, 4579, 2855,
       42050, 135487, 6730, 473, 19664, 60884, 5821, 13212, 274754, 34615,
       9287, 2302, 62417, 415, 13131, 125954, 34558, 3212, 20559, 33600,
       749, 720, 5372, 75235, 26843, 5081, 5286, 20031, 39782, 27261,
       40047, 11320, 20090, 14507, 3315, 878, 2209, 11488, 10082, 9924,
       398, 5431, 273, 0, 1368, 2070, 5752, 2808, 150, 2983, 43354, 5333,
       1915, 5340, 38390, 6908, 20835, 5162, 1716, 791, 888, 5219, 1426,
       312, 5954, 9408, 159, 19183, 18635, 10232, 45147, 4188, 17750, 422,
       76, 74, 5293, 726, 4421, 110, 61, 139, 2305, 5388, 1164, 15178,
       2143, 19001, 1712, 2050, 7937, 2166, 2283, 2422, 31977, 2341,
       45629, 5153, 17535, 12295, 1661, 4312, 91924, 2103, 4309, 1143,
       2815, 15827, 6321, 30354, 10019, 12958, 5163, 15847, 1206, 6745,
       3914, 5903, 5181, 5337, 32623, 10136, 8196, 5030, 20617, 15948,
       44735, 3622, 5272, 334, 13903, 922, 595, 1466, 4678, 2697, 5500,
       2195, 35920, 2657, 608, 12685, 5875, 14, 1036, 272, 4448, 216,
       5155, 81, 2039, 1331, 484, 20074, 265, 2184, 58116, 674, 223,
       10854, 5574, 3186, 5119, 908, 1778, 3195, 3594, 15643, 13, 5106,
       1461, 12, 59, 2082, 769, 4900, 17801, 4906, 6083, 500, 1290, 1662,
       3717, 2793, 4976, 2230, 2428, 1447, 257, 59049, 253, 11010, 299,
       758, 2007, 558, 1955, 158, 748, 10427, 102004, 5999, 15208, 32667,
       21061, 12537, 7566, 82, 3494, 11061, 1465, 7088, 10260, 5316, 4001,
       3026, 6782, 390, 343, 1068, 34201, 3854, 10296, 2854, 1127, 5466,
       1571, 21919, 730, 33145, 21376, 670, 5114, 60, 16656, 2255, 28993,
       10147, 10003, 3086, 5389, 14987, 29629, 15368, 33263, 6448, 5750,
       7483, 7525, 778, 15213, 1425, 2278, 5006, 2533, 3735, 7, 2595,
       5369, 2921, 6255, 2248, 2556, 2880, 4185, 1507, 481, 1, 1960, 1200,
       1380, 2066, 38, 5576, 16536, 19502, 11273, 8234, 6229, 3162, 3050,
       4370, 4799, 3711, 4458, 5026, 7035], dtype=object)

In [135]:
df["passengers \nto city 2"] = df["passengers \nto city 2"].replace("-",0)

In [136]:
df["passengers \nto city 2"] = df["passengers \nto city 2"].astype(int)

In [137]:
df["passengers \nto city 2"].dtypes

dtype('int64')

In [138]:
df["passengers \nfrom city 2"].unique()

array([5380, '-', 1514, 206, 4287, 4382, 320, 6970, 777, 10530, 3410,
       1712, 41179, 471, 1021, 1891, 3646, 334, 2168, 4780, 60, 2123,
       2804, 1908, 4369, 4908, 1563, 49110, 4306, 5031, 10201, 27144,
       4682, 17048, 4787, 106908, 244, 2323, 157, 14219, 4945, 22980,
       6427, 10284, 494, 3123, 1313, 1814, 216, 5219, 269, 29607, 11691,
       89237, 4211, 1481, 2257, 4783, 354, 22594, 5048, 5035, 5765, 17,
       5140, 2684, 4989, 2499, 5363, 4872, 5364, 30, 173, 750, 1386, 1632,
       497, 3337, 941, 314, 4564, 1574, 11410, 5502, 172, 51031, 2752,
       2165, 105, 14798, 4218, 5072, 2210, 73, 924, 12917, 1754, 10403,
       17105, 711, 6644, 54853, 4206, 374, 6790, 16639, 4852, 28386,
       26959, 2160, 3356, 4176, 3381, 2043, 450, 11603, 45314, 1639,
       24098, 67618, 18810, 50103, 863, 9075, 208730, 4924, 462, 5924,
       37029, 12133, 32115, 4555, 4406, 90026, 407, 20634, 4302, 36370,
       5150, 2982, 4691, 10993, 6300, 4039, 66286, 2140, 86172, 22195,
       253, 28774, 7803, 1422, 39108, 170416, 27181, 1600, 28357, 2324,
       21234, 77356, 12188, 2335, 6402, 20651, 2118, 6642, 1848, 511,
       8275, 13972, 9872, 1974, 37401, 2325, 15001, 5008, 33795, 1261,
       15702, 22455, 5534, 9658, 522, 5093, 25407, 2704, 17538, 4323,
       2092, 7470, 2286, 55464, 81, 930, 2274, 5258, 20784, 2792, 111,
       107, 453, 1880, 4188, 17707, 2213, 27432, 1704, 4771, 3344, 2311,
       77, 152, 1890, 2209, 5094, 9116, 680, 1113, 188, 41, 365, 217, 261,
       6143, 6812, 46239, 475, 5400, 847, 22, 10555, 4457, 5846, 623,
       7621, 3390, 4550, 24800, 59, 3803, 4760, 9098, 99, 39326, 5127,
       567, 95308, 4608, 4926, 16253, 61627, 6602, 10491, 109, 862, 1293,
       177, 39656, 49140, 5017, 4298, 22445, 2220, 105438, 2225, 5615,
       32368, 37251, 4717, 2288, 5443, 2188, 4834, 1105, 3486, 11993,
       17936, 8966, 693, 4895, 4460, 17581, 3514, 2211, 18387, 80, 303,
       24841, 240, 190, 22823, 25, 4943, 235, 4, 49739, 25389, 8903, 4836,
       4874, 5095, 5345, 64779, 1188, 4266, 5838, 4663, 14692, 4138, 1150,
       11029, 24838, 4987, 477, 2659, 2734, 3290, 12846, 3816, 7377, 3468,
       9050, 5572, 4806, 9418, 57792, 20931, 75089, 4246, 4910, 134671,
       16043, 50381, 5081, 8238, 285, 32388, 13615, 24942, 18326, 2136,
       3699, 5338, 3016, 43550, 132915, 7023, 322, 22559, 63783, 5825,
       14703, 275144, 34772, 12, 8691, 2230, 56878, 306, 14123, 121533,
       35960, 3428, 20967, 34567, 832, 663, 5322, 79308, 27734, 4350,
       4903, 20461, 42934, 27696, 42351, 11345, 20398, 14393, 885, 2357,
       3, 12832, 10144, 5555, 523, 5033, 311, 1, 1517, 1878, 6079, 3086,
       239, 2973, 42315, 5123, 1869, 5042, 40824, 6693, 19335, 4664, 1619,
       775, 870, 4938, 1097, 6557, 2084, 9903, 19406, 19226, 110, 9274,
       43861, 4582, 18120, 633, 5211, 833, 4777, 51, 2171, 5227, 1245,
       14761, 2008, 2235, 17851, 1772, 1494, 2234, 7748, 2313, 2306, 2747,
       34853, 2986, 43208, 5579, 16257, 12109, 1428, 4423, 93851, 2141,
       4465, 1469, 3188, 14909, 6696, 28274, 10652, 13725, 5347, 15592,
       1207, 6673, 3840, 5822, 5214, 5268, 31378, 11105, 8393, 4887,
       21339, 16157, 45717, 4029, 4968, 296, 13647, 761, 506, 1719, 4731,
       2555, 5391, 2096, 36559, 2885, 545, 12125, 6254, 1516, 946, 201,
       4567, 277, 4761, 2026, 1306, 599, 20642, 167, 2147, 59962, 820,
       332, 10371, 5607, 3176, 4588, 16, 712, 1675, 4262, 4629, 14145,
       5231, 1410, 47, 2110, 896, 4518, 18592, 4727, 6112, 487, 1475,
       1699, 3684, 2618, 4884, 1977, 2333, 1440, 249, 57189, 193, 10011,
       396, 755, 2146, 730, 2059, 395, 861, 11608, 107235, 5519, 14959,
       34466, 23256, 12996, 8909, 69, 2840, 10456, 1837, 7450, 7, 10288,
       5714, 4052, 2828, 6498, 408, 280, 900, 34768, 3970, 10541, 2927,
       1279, 5464, 1685, 20908, 1598, 32594, 18373, 547, 5198, 17264,
       2282, 28576, 9848, 1310, 11008, 2929, 5346, 15775, 29343, 16091,
       33153, 6277, 6142, 7827, 7342, 799, 15598, 5, 168, 1282, 1683, 151,
       3097, 3146, 2479, 6337, 2650, 6174, 2730, 2810, 2879, 4417, 1895,
       329, 1436, 1911, 1647, 2180, 4363, 13788, 18849, 13940, 8940, 4735,
       3477, 4893, 3289, 5083, 6732], dtype=object)

In [139]:
df["passengers \nfrom city 2"] = df["passengers \nfrom city 2"].replace("-",0)

df["passengers \nfrom city 2"] = df["passengers \nfrom city 2"].astype(int)

In [140]:
df["passengers \nfrom city 2"].dtypes

dtype('int64')

In [141]:
df['freight \nto city 2'].dtypes

dtype('O')

In [142]:
df["freight \nto city 2"].unique()

array([0, '-', 19.084, 0.003, 15.369, 0.081, 3.025, 7.662, 0.335, 16.058,
       0.169, 0.846, 1.018, 0.04, 0.044, 0.306, 9.0749,
       459.53163000000006, 0.086, 21.948, 22.889, 246.19710000000003,
       26.23, 10.255, 3.685, 1867.3134954999996, 1.506, 0.061, 0.278,
       16.235, 26.041, 170.168, 0.2, 5.083, 2.773, 35.497, 256.88371,
       45.201, 950.5565522999999, 0.055, 40.698, 82.16307, 19.08, 10.113,
       0.901, 5.229, 2.3, 0.002, 13.328, 2.471, 32.542, 0.056, 0.046,
       11.604, 0.119, 35.6705, 5.853, 3.8914999999999997, 3.625, 0.382,
       51.77973, 12.395, 101.59169, 0.347, 2.315, 40.633, 31.85649,
       30.62787, 0.049, 0.072, 0.012, 32.079, 151.51708,
       216.13400000000001, 846.56747, 31.3, 91.96, 0.432, 7.626,
       3472.7106776, 0.075, 19.591, 17.939, 62.45451, 211.62536, 0.62,
       502.82, 3.367, 90.11, 0.354, 186.617, 0.447, 0.188, 11.307,
       0.5489999999999999, 1.508, 289.046, 0.171, 1156.9180299999998,
       19.651, 319.043, 1.02, 6.279999999999999, 1532.0100787, 82.863,
       0.27, 174.94980999999996, 0.151, 66.774, 521.095, 39.816, 0.027,
       5.786, 174.848, 0.117, 0.042, 0.689, 4.689, 18.371, 0.616, 0.192,
       54.263999999999996, 0.009, 21.366, 4.739, 59.748810000000006,
       2.074, 71.607, 0.14, 0.015, 17.212, 0.008, 13.849, 0.001, 0.947,
       78.107, 1.233, 4.607, 0.759, 26.851, 0.945, 20.398999999999997,
       4.162, 0.285, 0.078, 44.208, 9.551, 100.0817246, 0.35, 4.835,
       45.455, 19.362, 1.542, 23.023, 21.8707, 6.791, 116.32900000000001,
       3.905, 25.722, 0.349, 36.628, 4.714, 0.239, 2910.000571399998,
       0.949, 3.336, 24.767, 460.60952, 51.232, 35.383, 0.233, 0.216,
       0.109, 47.09292, 245.59643999999997, 0.501, 34.123, 8.9615, 0.023,
       539.9844301, 0.047, 17.268, 148.32193999999998, 346.24502, 15.737,
       0.032, 33.332, 0.039, 1.202, 0.6590199999999999, 3.387, 1.485,
       10.193, 0.381, 0.172, 1.361, 0.369, 35.044, 0.007, 172.312, 0.439,
       0.779, 54.12, 1.781, 125.33500000000001, 29.869, 72.046426, 46.837,
       2.221, 0.814, 13.707, 12.233, 6.378, 65.801068, 1.822, 5.745,
       9.445, 1.5726999999999998, 1.865, 0.006, 2.497, 1.73, 0.051, 0.365,
       1.926, 0.132, 29.133, 8.706, 29.415, 0.544, 239.93667999999997,
       49.749840000000006, 1105.1591240999999, 0.231, 8.446,
       1600.3929732000004, 128.088, 415.18619149999995, 0.819, 1.974,
       47.6825146, 73.61838, 0.266, 16.538000000000004, 0.252, 0.844,
       0.529, 0.175, 520.7543206999999, 1798.1231237000002, 9.057,
       157.8476766, 309.4211278, 32.612, 35.783, 6187.1368901, 215.6155,
       27.803, 0.18, 415.03354979999995, 43.886421, 1493.4739353999998,
       285.6810115999999, 5.349, 29.253, 303.363, 5.508, 357.98922, 52.5,
       0.81, 36.865, 125.4885, 41.29148000000001, 79.3995,
       160.41562000000002, 62.3035, 105.34750030000001, 0.706, 0.176,
       1.411, 6.942, 12.316, 30.792, 8.83, 1.054, 29.796999999999997,
       2.366, 18.716, 11.75284, 1.27, 89.06719, 0.095, 0.016, 82.98,
       71.17099999999999, 3.523, 206.44992, 2.198, 54.82902, 15.502,
       0.101, 0.147, 58.271, 0.138, 35.844, 1.93, 0.265, 0.307, 48.06,
       1.211, 148.69025, 1.181, 43.599, 3.006, 0.083, 696.6209999999999,
       0.293, 0.005, 39.938, 30.79, 58.943000000000005, 15.413, 0.492,
       1.504, 26.264, 6.086, 0.717, 4.94, 2.362, 4.0575, 1.832, 2.122,
       4.629, 7.09958, 2.216, 39.003, 5.564, 198.186, 0.033, 33.652,
       0.059, 109.132655, 0.682, 10.809, 2.32, 0.022, 5.13, 3.798,
       154.236, 0.026, 355.1398425, 53.934999999999995, 0.917, 1.527,
       16.21879, 0.679, 1.602, 1.626, 0.004, 0.141, 1.138, 4.754, 0.157,
       110.482, 2.752, 16.381999999999998, 0.356, 45.315, 716.23964,
       13.05, 34.61, 281.5886, 90.47363, 34.948, 7.776, 0.202, 46.499,
       2.082, 37.671, 1.792, 2.1, 55.0285, 2.751, 53.171, 6.127, 1.892,
       13.724, 2.19, 122.8407855, 127.89516940000001, 11.309, 96.519,
       1.03, 18.9395919, 63.361, 24.925, 0.128, 2.979, 26.049500000000002,
       32.205659999999995, 24.733, 86.5111362, 37.060295499999995, 22.995,
       2.2510000000000003, 0.19899999999999998, 10.959, 0.338, 0.963,
       4.045, 0.236, 59.103, 0.12, 2.148, 1.387, 0.104, 3.036, 27.299,
       0.334, 0.565, 8.143, 1.738, 0.513, 2.212, 2.42, 1.087, 6.588],
      dtype=object)

In [143]:
df["freight \nto city 2"] = df["freight \nto city 2"].replace("-",0)

In [144]:
df["freight \nto city 2"].dtypes

dtype('float64')

In [145]:
df["freight \nfrom city 2"].dtypes

dtype('O')

In [146]:
df["freight \nfrom city 2"].unique()

array([0.083, '-', 0, 0.793, 6.047, 0.001, 45.264, 0.021, 54.803, 1.805,
       21.513, 222.37400000000002, 0.268, 0.016, 3.03, 0.566, 0.426,
       12.977, 22.403, 337.65824, 1.433, 33.558, 234.34387, 23.671, 9.189,
       0.167, 1508.0505969, 0.823, 4.53, 2.622, 6.568, 88.413, 0.055,
       6.521, 17.743, 154.90432, 17.35, 686.6918835, 0.106, 2.624,
       122.619, 0.489, 4.435, 0.241, 0.4, 8.6, 2.051, 23.16, 5.361, 7.449,
       0.941, 1.631, 0.224, 1.108, 1.921, 0.322, 26.9555, 0.175, 0.279,
       27.1705, 1.313, 1.354, 1.302, 109.88250000000001, 0.13, 9.657,
       12.693, 3.64, 309.11385, 0.044, 27.046110000000002, 10.219,
       22.439159999999998, 66.92272, 0.04, 0.49, 0.197, 0.835, 0.003,
       15.793, 32.636, 156.768, 558.2062099999999, 18.691, 37.385, 3.631,
       4251.964875199999, 0.169, 20.717, 57.114, 29.68638, 101.35647,
       0.622, 151.98700000000002, 19.47, 39.592, 0.002,
       263.71999999999997, 7.091, 0.632, 1.051, 98.315, 0.209, 829.69985,
       0.142, 93.738, 0.084, 32.754, 1599.1871575, 29.991, 0.549,
       53.43935999999999, 4.027, 270.08898, 2.699, 4.088, 15.25, 9.299,
       80.602, 0.917, 35.024, 5.976, 104.54735000000001, 0.048, 6.311,
       1.041, 120.7110225, 0.144, 50.9725, 2.157, 25.145, 872.0829875, 1,
       1.151, 8.208, 40.982, 1.918, 4.678, 18.677, 1.576, 132.623, 27.377,
       0.872, 0.004, 0.006, 0.008, 0.182, 0.639, 0.452, 36.662, 9.003,
       141.0944113, 1.162, 0.133, 37.414, 2.493, 0.012, 0.095, 9.162,
       2.008, 179.34756070000003, 0.177, 25.076, 0.098, 31.443, 4.482,
       4.487, 2382.2926337000004, 5.313, 5.284, 42.094, 298.9207, 15.742,
       76.823, 32.46483, 261.2743, 0.01, 15.144, 49.21, 0.028, 753.462871,
       6.933, 103.15574000000001, 172.68836000000002, 1.079, 2.508, 0.017,
       6.086, 30.596, 11.789, 18.49, 0.368, 23.164, 9.354, 189.5641834,
       26.634, 0.117, 1.995, 192.6991558, 25.583, 196.1927, 26.519, 1.879,
       4.982, 11.21, 19.924, 11.524, 97.0731159, 4.218, 27.791, 6.824,
       0.332, 0.181, 28.54593, 7.115, 4.221, 2, 0.221, 8.869, 4.853,
       13.954, 22.336, 93.20324550000001, 55.51551, 188.49518,
       973.3986494999998, 164.593, 187.9388889, 0.22, 3.236, 138.044,
       15.61585, 0.138, 0.024, 0.907, 0.147, 288.57437300000004,
       2326.9397708000006, 0.501, 31.518909999999998, 81.842, 66.474,
       3.102, 3976.1334357000005, 68.959, 6.912, 89.275, 8.727,
       1356.8311950999998, 24.502, 0.034, 55.662591899999995, 58.199,
       0.799, 343.69642, 97.786, 7.387, 52.4375, 13.921399999999998, 2.22,
       38.57384, 24.791999999999998, 7.7589999999999995, 2.361, 23.589,
       7.7620000000000005, 13.717, 0.418, 0.394, 0.029, 7.742000000000001,
       16.604, 0.904, 40.56945, 1.41, 23.80845, 0.21, 4.963, 0.045, 0.936,
       11.75357, 38.905, 114.027, 8.524, 463.28404, 3.362, 122.27339,
       0.039, 0.196, 2.227, 22.105, 159.264, 0.395, 35.742, 1.069,
       193.37982, 0.007, 30.939, 57.609, 1055.1310966, 0.05, 9.483, 7.795,
       144.995, 0.419, 0.24, 5.206, 3.453, 5.742, 0.6590199999999999,
       0.51, 40.333, 1.252, 3.514, 3.726, 0.249, 24.708190000000002,
       1.695, 26.749000000000002, 55.54, 0.022, 0.09, 22.811, 0.035,
       110.882, 0.657, 56.699, 0.487, 1.687, 0.779, 0.356, 67.729, 0.091,
       330.70365000000004, 0.015, 20.617, 0.837, 8.779, 2.80285, 3.1135,
       6.657500000000001, 0.544, 2.093, 0.994, 0.681, 7.804, 7.172, 0.292,
       317.611847, 0.073, 63.281000000000006, 35.997, 1034.2935725,
       28.162, 8.437, 64.78074, 197.871, 1.047, 0.31, 0.237, 4.785,
       76.189, 14.311, 12.397, 5.091, 1.9125, 202.60389759999998, 0.761,
       73.11500000000001, 0.674, 12.96, 10.56, 11.257, 108.43599999999999,
       25.118969999999997, 1.344, 36.196, 0.134, 93.2875, 13.906,
       21.74051, 0.019, 13.3735, 10.05198, 24.93866, 2.5055, 4.456, 55.25,
       16.243, 0.291, 0.58, 5.357, 1.241, 17.251, 7.19, 0.215, 2.50557,
       0.473, 0.018, 0.105, 0.068, 0.357, 11.921, 72.451, 3.028, 0.942,
       4.205], dtype=object)

In [147]:
df["freight \nfrom city 2"] = df["freight \nfrom city 2"].replace("-",0)

In [148]:
df["freight \nfrom city 2"].dtypes

dtype('float64')

In [149]:
df["mail \nto city 2"].dtypes

dtype('O')

In [150]:
df["mail \nto city 2"].unique()

array([0, '-', 1.375, 1.625, 4.149, 0.004, 2.183, 2.263, 0.286, 3.766,
       1.89, 1.662, 0.544, 7.185799999999999, 0.595, 1.783, 0.69, 1.292,
       0.006, 1.084, 2.601, 18.8166, 0.643, 2.767, 3.53684, 1.188, 1.523,
       0.858, 0.256, 8.26, 10.147, 1.223, 0.015, 0.5, 0.711, 0.08, 1.231,
       1.381, 3.417, 0.666, 8.15, 2.074, 8.022, 11.842699999999999, 8.774,
       18.024, 7.178, 1.542, 5.493, 24.066989999999997, 2.4256, 14.25108,
       0.244, 31.564, 4.126, 4.258, 11.952, 0.23, 2.828, 0.148, 19.884,
       16.409, 0.757, 15.41, 2.681, 13.158, 15.20406, 4.667, 0.679,
       16.095, 1.176, 12.843300000000001, 7.134, 2.167, 3.034, 0.685,
       0.952, 0.507, 0.88, 10.43, 4.024, 4.958880000000001, 2.842, 6.081,
       15.007190000000001, 0.521, 4.648, 1.402, 1.586, 0.089, 5.27558,
       0.59, 5.797, 0.192, 0.052, 7.539, 2.287, 5.21, 0.536, 0.024, 0.136,
       17.936999999999998, 1.097, 1.072, 7.775163000000001, 0.501,
       4.2059999999999995, 1.389, 1.11, 1.994, 0.612, 24.707230000000003,
       4.868, 13.921, 3.918, 5.538, 13.51, 9.841, 1.562, 10.497,
       16.729049999999997, 30.982630000000004, 5.23, 37.97193, 5.058,
       2.111, 1.835, 0.303, 0.299, 0.261, 7.295, 3.447, 7.673, 5.64,
       1.008, 4.02, 5.108, 1.37605, 0.408, 0.151, 0.196, 0.426, 1.051,
       0.376, 4.7293400000000005, 0.187, 7.354, 0.524, 0.16, 0.622, 1.085,
       0.168, 6.207, 2.732, 0.273, 10.591, 27.25471, 2.81, 35.236389,
       7.194, 10.544737000000001, 8.43, 14.427450000000004, 8.046,
       25.19865, 12.527, 23.50927, 54.77383999999999, 3.395,
       46.23373900000001, 50.2824, 4.045, 0.028, 44.962599999999995,
       17.8335, 1.959, 41.56569, 2.0454999999999997, 17.04, 22.468,
       8.70215, 16.762, 4.394202999999999, 3.194, 1.343,
       9.342784999999997, 0.0342, 7.510499999999999, 13.810904,
       9.556465999999999, 6.74064, 5.27, 4.235, 6.777, 0.272, 0.406,
       2.047, 6.559, 0.821, 9.415, 4.312, 7.25676, 6.363, 0.651, 0.61,
       11.235, 0.166, 5.225, 0.374, 1.356, 0.573, 9.093, 9.094, 2.237,
       6.629, 7.327, 1.045, 27.94, 0.519, 0.22, 10.815, 4.531, 4.565,
       13.843, 1.147, 3.702, 0.702, 1.668, 8.142, 10.237, 4.832, 0.943,
       1.112, 8.33, 11.353, 0.55, 15.451, 0.139, 0.888, 0.568, 9.51594,
       0.661, 1.194, 0.828, 2.147, 4.993, 1.92633, 0.551, 1.25,
       28.730709999999995, 11.425, 14.03653, 11.574, 25.57784, 4.67928,
       2.991, 5.521, 1.671, 0.071, 3.152, 4.053, 3.51, 0.378, 0.897,
       0.922, 82.695, 38.10368, 13.883128, 1.98, 18.785, 10.63109, 5.227,
       2.97065, 0.323, 2.97, 4.796327999999999, 4.374543, 7.27433,
       5.1535969999999995, 5.533, 9.25, 2.27, 1.805, 0.567, 0.352, 0.201,
       0.095, 0.033, 0.24, 2.439], dtype=object)

In [151]:
df["mail \nto city 2"] = df["mail \nto city 2"].replace("-",0)

In [152]:
df["mail \nto city 2"].dtype

dtype('float64')

In [153]:
df["mail \nfrom city 2"].dtypes

dtype('O')

In [154]:

df["mail \nfrom city 2"].unique()

array([0, '-', 0.567, 4.984, 5.07576, 0.001, 1.281, 0.149,
       7.419040000000001, 0.818, 1.007, 1.26, 4.486, 1.062, 0.229, 0.233,
       22.274900000000002, 0.066, 0.045, 2.011, 1.488, 2.384,
       1.7206100000000002, 2.322, 39.585827, 6.746, 3.264, 2.089, 0.085,
       1.055, 0.131, 1.336, 4.487, 6.635, 1.25, 0.638, 24.332, 7.186,
       1.918, 0.02612, 0.253, 4.12394, 0.005, 0.043, 7.5611, 1.07, 20.785,
       1.952, 0.127, 0.569, 6.3889, 2.14202, 0.941, 4.699,
       6.8729499999999994, 2.052, 0.054, 21.496, 2.469, 1.139, 0.809,
       40.709737000000004, 0.133, 5.08455, 0.929, 30.337, 1.729, 2.412,
       2.167, 11.512, 6.91391, 2.268, 1.654, 118.159, 34.119792000000004,
       5.721, 0.161, 0.452, 4.051, 1.5, 3.346, 0.013, 2.084, 6.068, 0.291,
       0.3, 1.104, 5.04, 19.54835, 0.279, 17.879002, 0.961, 6.785, 0.082,
       22.11047, 1.49, 9.546, 11.835, 2.27, 11.021, 0.561, 0.492, 10.679,
       0.306, 26.642980000000005, 0.546, 5.402, 0.686, 0.955, 3.537,
       12.18317, 1.698, 7.446, 0.597, 0.495, 54.23857700000001, 0.024,
       3.176, 21.894, 0.977, 1.234, 9.09, 4.084, 2.252, 10.06616, 0.252,
       20.046409000000004, 0.632, 3.491, 1.03, 0.396, 0.158, 4.966, 0.225,
       1.831, 5.9967, 4.104, 4.38152, 0.35, 3.1004399999999994, 5.547,
       0.342, 8.915357999999998, 25.406, 1.582, 1.282, 5.397, 0.311,
       1.782, 8.902, 0.1658, 11.18935, 0.738, 14.19, 6.105,
       6.0767299999999995, 0.061, 8.471, 9.789, 25.99070600000001,
       37.13105000000001, 21.982, 20.750999999999998, 2.091, 43.47,
       75.60184100000001, 26.137, 0.355, 18.028494000000002,
       0.022590000000000002, 2.72178, 8.38291, 0.021, 8.002, 0.303,
       45.266, 2.013, 0.697, 8.837419999999998, 2.869,
       0.10720000000000002, 2.677, 9.146, 4.158, 3.475, 0.406, 0.272,
       1.426, 2.397, 4.063, 6.682, 0.491, 6.908, 1.438, 13.3303, 0.338,
       5.186, 1.322, 0.875, 7.78, 7.143, 2.168, 1.364, 0.018, 28.149652,
       0.002, 0.226, 2.67, 4.021, 1.232, 4.454, 1.228, 1.671, 3.483,
       0.205, 0.655, 0.028, 4.045, 2.701, 1.363, 10.747900000000001,
       0.635, 2.163, 10.358, 3.674, 0.877, 20.8572, 0.414, 1.995, 4.529,
       8.086590000000001, 1.183, 6.475, 1.019, 25.78574, 0.312, 2.015,
       23.873629, 3.669, 7.713, 2.493, 1.217, 0.89, 0.532, 8.828,
       20.633313, 5.407, 0.784, 0.757, 6.217, 2.131, 16.07967,
       5.454999999999999, 3.656, 0.23027, 0.18, 5.60458, 0.835, 0.034,
       2.209, 3.288, 1.125, 1.27, 0.513, 0.042, 0.2, 0.297, 2.647],
      dtype=object)

In [155]:
df["mail \nfrom city 2"] = df["mail \nfrom city 2"].replace("-",0)

In [156]:
df["mail \nfrom city 2"].dtypes

dtype('float64')

In [157]:
print(df.columns.tolist())

['city 1', 'city 2', 'passengers \nto city 2', 'passengers \nfrom city 2', 'freight \nto city 2', 'freight \nfrom city 2', 'mail \nto city 2', 'mail \nfrom city 2', 'OD Pair']

In [158]:
df.isnull().sum()

city 1                      0
city 2                      0
passengers \nto city 2      0
passengers \nfrom city 2    0
freight \nto city 2         0
freight \nfrom city 2       0
mail \nto city 2            0
mail \nfrom city 2          0
OD Pair                     0
dtype: int64

In [159]:
df= df.sort_values( by =("OD Pair"))

In [160]:
df

,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2,OD Pair
2,ADAMPUR,Ghaziabad,1139,1514,0.000,0.000,0.00,0.0,ADAMPUR-Ghaziabad
0,ADAMPUR,MUMBAI,5278,5380,0.000,0.083,0.00,0.0,ADAMPUR-MUMBAI
1,ADAMPUR,NANDED,578,0,0.000,0.000,0.00,0.0,ADAMPUR-NANDED
3,AGARTALA,AHMEDABAD,0,206,0.000,0.793,0.00,0.0,AGARTALA-AHMEDABAD
4,AGARTALA,BAGDOGRA,2221,4287,0.000,0.000,0.00,0.0,AGARTALA-BAGDOGRA
...,...,...,...,...,...,...,...,...,...
639,TIRUPATI,VIJAYAWADA,1380,1647,0.104,0.018,0.24,0.0,TIRUPATI-VIJAYAWADA
640,TIRUPATI,VISAKHAPATNAM,2066,2180,0.001,0.105,0.00,0.2,TIRUPATI-VISAKHAPATNAM
641,TRIVANDRUM,VISAKHAPATNAM,38,0,0.000,0.000,0.00,0.0,TRIVANDRUM-VISAKHAPATNAM
642,VARANASI,VISAKHAPATNAM,415,395,0.000,0.068,0.00,0.0,VARANASI-VISAKHAPATNAM
643,VIJAYAWADA,VISAKHAPATNAM,5576,4363,0.005,0.357,0.00,0.0,VIJAYAWADA-VISAKHAPATNAM

In [161]:
df["OD pair2"] = df["city 2"] + "-" + df["city 1"]

In [162]:
df

,city 1,city 2,passengers \nto city 2,passengers \nfrom city 2,freight \nto city 2,freight \nfrom city 2,mail \nto city 2,mail \nfrom city 2,OD Pair,OD pair2
2,ADAMPUR,Ghaziabad,1139,1514,0.000,0.000,0.00,0.0,ADAMPUR-Ghaziabad,Ghaziabad-ADAMPUR
0,ADAMPUR,MUMBAI,5278,5380,0.000,0.083,0.00,0.0,ADAMPUR-MUMBAI,MUMBAI-ADAMPUR
1,ADAMPUR,NANDED,578,0,0.000,0.000,0.00,0.0,ADAMPUR-NANDED,NANDED-ADAMPUR
3,AGARTALA,AHMEDABAD,0,206,0.000,0.793,0.00,0.0,AGARTALA-AHMEDABAD,AHMEDABAD-AGARTALA
4,AGARTALA,BAGDOGRA,2221,4287,0.000,0.000,0.00,0.0,AGARTALA-BAGDOGRA,BAGDOGRA-AGARTALA
...,...,...,...,...,...,...,...,...,...,...
639,TIRUPATI,VIJAYAWADA,1380,1647,0.104,0.018,0.24,0.0,TIRUPATI-VIJAYAWADA,VIJAYAWADA-TIRUPATI
640,TIRUPATI,VISAKHAPATNAM,2066,2180,0.001,0.105,0.00,0.2,TIRUPATI-VISAKHAPATNAM,VISAKHAPATNAM-TIRUPATI
641,TRIVANDRUM,VISAKHAPATNAM,38,0,0.000,0.000,0.00,0.0,TRIVANDRUM-VISAKHAPATNAM,VISAKHAPATNAM-TRIVANDRUM
642,VARANASI,VISAKHAPATNAM,415,395,0.000,0.068,0.00,0.0,VARANASI-VISAKHAPATNAM,VISAKHAPATNAM-VARANASI
643,VIJAYAWADA,VISAKHAPATNAM,5576,4363,0.005,0.357,0.00,0.0,VIJAYAWADA-VISAKHAPATNAM,VISAKHAPATNAM-VIJAYAWADA

In [163]:
df[['city3', 'city4']] = df['OD pair2'].str.split('-', expand=True)

In [164]:
df1= df[["OD Pair", "city 1","city 2" , "passengers \nto city 2" , "freight \nto city 2" , "mail \nto city 2"]]

In [165]:
df2= df[["OD pair2","city3", "city4", "passengers \nfrom city 2",	"freight \nfrom city 2"	,"mail \nfrom city 2"]]

In [166]:
df1.columns=["OD PAIRS", "city 1" , "city2", "passengers" , "freight", "mail"]

In [167]:





df2.columns=["OD PAIRS", "city 1" , "city2", "passengers" , "freight", "mail"]

In [168]:
df_final=pd.concat([df1,df2], axis= 0)

In [169]:
df_final = df_final.melt(
    id_vars=df_final.columns[:3],
    value_vars=df_final.columns[3:],
    var_name='type',
    value_name='value'
)

In [170]:
print(df_final.columns.tolist())

['OD PAIRS', 'city 1', 'city2', 'type', 'value']

In [171]:
df_final

                      OD PAIRS         city 1       city2        type   value
0            ADAMPUR-Ghaziabad        ADAMPUR   Ghaziabad  passengers  1139.0
1               ADAMPUR-MUMBAI        ADAMPUR      MUMBAI  passengers  5278.0
2               ADAMPUR-NANDED        ADAMPUR      NANDED  passengers   578.0
3           AGARTALA-AHMEDABAD       AGARTALA   AHMEDABAD  passengers     0.0
4            AGARTALA-BAGDOGRA       AGARTALA    BAGDOGRA  passengers  2221.0
...                        ...            ...         ...         ...     ...
3937       VIJAYAWADA-TIRUPATI     VIJAYAWADA    TIRUPATI        mail     0.0
3938    VISAKHAPATNAM-TIRUPATI  VISAKHAPATNAM    TIRUPATI        mail     0.2
3939  VISAKHAPATNAM-TRIVANDRUM  VISAKHAPATNAM  TRIVANDRUM        mail     0.0
3940    VISAKHAPATNAM-VARANASI  VISAKHAPATNAM    VARANASI        mail     0.0
3941  VISAKHAPATNAM-VIJAYAWADA  VISAKHAPATNAM  VIJAYAWADA        mail     0.0

[3942 rows x 5 columns]

In [172]:
df_final=df_final.sort_values(by=["OD PAIRS"])

In [180]:
df_final[df_final["OD PAIRS"]=="MUMBAI-JAIPUR"]

           OD PAIRS  city 1   city2        type        value
596   MUMBAI-JAIPUR  MUMBAI  JAIPUR  passengers   4799.00000
3224  MUMBAI-JAIPUR  MUMBAI  JAIPUR        mail      0.00000
1166  MUMBAI-JAIPUR  MUMBAI  JAIPUR  passengers  59962.00000
2480  MUMBAI-JAIPUR  MUMBAI  JAIPUR     freight    330.70365
3794  MUMBAI-JAIPUR  MUMBAI  JAIPUR        mail     20.85720
1910  MUMBAI-JAIPUR  MUMBAI  JAIPUR     freight      2.21200

In [182]:
pd.set_option('display.max_rows', None)

In [188]:
df_final[df_final["OD PAIRS"]=="JAIPUR-MUMBAI"]

           OD PAIRS  city 1   city2        type         value
1823  JAIPUR-MUMBAI  JAIPUR  MUMBAI     freight    355.139842
1253  JAIPUR-MUMBAI  JAIPUR  MUMBAI  passengers   4893.000000
2567  JAIPUR-MUMBAI  JAIPUR  MUMBAI     freight      4.205000
509   JAIPUR-MUMBAI  JAIPUR  MUMBAI  passengers  58116.000000
3137  JAIPUR-MUMBAI  JAIPUR  MUMBAI        mail      4.993000
3881  JAIPUR-MUMBAI  JAIPUR  MUMBAI        mail      0.000000